seed: 0
data:
  # meta data
  data_dir: 'data'
  dataset_name: 'duffing'
  signals_path: 'config\data\exo_input\signals'
  ds_path: ''

  # create new dateset or retrieve existing
  pinn_sampling: split_traj # split_set, split_traj, no_physics
  gen_mode: backward #'forward' or 'backward' or 'time_convergence'
  # validation
  validation:
    method: horizon # horizon, different sets, none
    params:
        time: 10 # time in sec
#        window_size: 1

  sim_time:
    _target_: src.simulators.types.SimTime
    t0: 0.0 # in seconds
    tn: 50.0  # in seconds
    eps: 0.05 #  Make sure to take the Shannon's theorem into account #todo: add a checker for shannon theorem depending on the system used
  solver:
    _target_: src.simulators.solvers.get_solver
    name: rk4

  ph_sampler:
    _target_: src.simulators.sampler.get_sampler
    sampler_type: lhs
    seed: 8888
    sample_space: [ [ -1,1 ],[ -1,1 ] ]

  dataloader:
    seed: ${seed}
    batch_size: 32
    shuffle: True

defaults:
  - _self_
  - data/exo_input: duff
  - data/system: duff
  - data/observer: duff
  - model: mlp
  - trainer: supervised




 